SCALE_FACTOR =  2.5
SCREEN_VIRTUAL_WIDTH = 512
SCREEN_VIRTUAL_HEIGHT = 288

BLOCK_WIDTH = 32 * SCALE_FACTOR
BLOCK_HEIGHT = 32 * SCALE_FACTOR

BOARD_OFFSET_X = 250 * SCALE_FACTOR
BOARD_OFFSET_Y = 16 * SCALE_FACTOR
